import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic';


let DynamicTable = dynamic(import('./gol_table'), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Game Of Life</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='grid'>
        <h1>Game Of Life</h1>
          <DynamicTable />
        </div>
      </main>
    </>
  )
}
